import Nav from "./Nav";
import "./global.css";
import { Inter } from "@next/font/google";
import { Anonymous_Pro } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const anonymous_pro = Anonymous_Pro({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: ["--font-anonymous-pro"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${anonymous_pro.variable} bg-slate-500 h-screen`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
